version: '3'
services:
  mc-server:
    image: mc
    volumes:
    - ~/.aws/:/root/.aws:ro
    env_file:
      - .env
    ports:
    - "25565:25565"
    stdin_open: true
    tty: true
    container_name: mc-server