on:
    push:
      branches:
        - main
      paths:
        - "server-wrapper/**"

name: Build Server Wrapper

env:
    IMAGE_NAME: ${{ github.event.act && 'localhost:8080' || 'ghcr.io' }}/${{ vars.IMAGE_REPO }}:latest

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - if: ${{ !github.event.act }}
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
        - run: docker build -t $IMAGE_NAME ./server-wrapper
        - run: docker push $IMAGE_NAME