on:
    push:
      branches:
        - main
      paths-ignore:
        - ".github/workflows/run.yaml"
        - "README.md"
        - ".gitignore"

name: Build Server Wrapper

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        - uses: actions/checkout@v2
        - uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - run: |
            touch .env
            docker compose build
            docker push ghcr.io/jackblake-zkq/easy-mcs:latest