on:
    push:
      branches:
        - main

name: CI

env:
    IMAGE_NAME: ${{ github.event.act && 'localhost:8080' || 'ghcr.io' }}/jackblake-zkq/wrapped-mc:latest

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - if: ${{ !github.event.act }}
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
        - run: docker build -t $IMAGE_NAME .
        - run: docker push $IMAGE_NAME